version: '3'
services:
  vbo-rest:
    image: 'vbo-rest:latest'
    container_name: 'vbo-rest'
    ports:
        - '80:80'
        - '4443:4443'
        - '443:443'
    volumes:
        - ./config:/var/www/html/vbo-config
        - /home/veeamadmin/vbo-365/vbo-docker/certs:/var/www/html/vbo-certs